#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cleanup() {
  rm -f node_modules/prettier
}

# format with prettier2
ln -sf ./prettier2 node_modules/prettier

# cleanup when done
trap cleanup EXIT

# pretty-quick on code base
npx pretty-quick --staged --pattern 'src/**/*.ts'
